# Generated by Django 4.1.3 on 2023-01-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='taille_vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='type_vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField()),
                ('cout', models.IntegerField()),
                ('taille_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.taille_vehicule')),
                ('type_vehicule_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.type_vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='location_tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_jour', models.IntegerField()),
                ('taille_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.taille_vehicule')),
                ('type_vehicule_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.type_vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_location', models.DateTimeField()),
                ('date_retour', models.DateTimeField()),
                ('cout', models.IntegerField()),
                ('client_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.client')),
                ('vehicule_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.vehicule')),
            ],
        ),
    ]
