# Generated by Django 4.1.3 on 2023-01-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='statu',
            field=models.BooleanField(default=0),
        ),
    ]
