# Generated by Django 4.1.3 on 2023-01-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=50)),
                ('Telephone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('descript', models.TextField()),
                ('photo', models.ImageField(upload_to='img_agent', verbose_name='photo de Agent')),
                ('date_servie', models.DateField(default='0')),
                ('statu', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('adresse', models.CharField(max_length=20)),
                ('chambre', models.IntegerField(default='1')),
                ('garage', models.IntegerField(default='1')),
                ('douche', models.IntegerField(default='1')),
                ('date_cons', models.DateField()),
                ('prix', models.IntegerField()),
                ('superficie', models.FloatField()),
                ('descript', models.TextField()),
                ('ville', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=20)),
                ('photo_pri', models.ImageField(upload_to='img_Maison', verbose_name='photo principale')),
                ('photo1', models.ImageField(default='0', upload_to='img_Maison', verbose_name='photo de Maison')),
                ('photo2', models.ImageField(default='0', upload_to='img_Maison', verbose_name='photo de Maison')),
                ('photo3', models.ImageField(default='0', upload_to='img_Maison', verbose_name='photo de Maison')),
                ('agent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Maison.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Cocher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=0, max_length=40)),
                ('mail', models.CharField(default=0, max_length=40)),
                ('message', models.CharField(default=0, max_length=400)),
                ('client', models.CharField(default=0, max_length=40)),
                ('propriete_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Maison.propriete')),
            ],
        ),
    ]
