# Generated by Django 4.1.3 on 2023-01-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='photo',
            field=models.ImageField(default=0, upload_to='', verbose_name='photo de chambre'),
        ),
    ]
