# Generated by Django 4.1.3 on 2023-01-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_alter_chambre_date_creation_alter_chambre_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='date_creation',
            field=models.DateField(default='null'),
        ),
    ]
