# Generated by Django 4.1.3 on 2022-12-26 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('patte', models.CharField(max_length=20)),
                ('poid', models.IntegerField()),
                ('vitesse', models.CharField(max_length=20)),
                ('famil', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sauvage.famille')),
            ],
        ),
    ]
